- name: Stop and disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Check if /etc/resolv.conf is a symbolic link
  stat:
    path: /etc/resolv.conf
  register: resolv_conf

- name: Ensure /etc/resolv.conf is not a symbolic link
  file:
    path: /etc/resolv.conf
    state: absent
  when: resolv_conf.stat.islnk is defined and resolv_conf.stat.islnk
  become: true

- name: Check if 10.0.0.1 is reachable
  wait_for:
    host: 10.0.0.1
    port: 53
    timeout: 5
  register: result_production
  ignore_errors: true

- name: Set nameserver in resolv.conf to 10.0.0.1
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 10.0.0.1
    backup: yes
  become: true
  when: result_production is succeeded

- name: Check if 192.168.178.2 is reachable
  wait_for:
    host: 192.168.178.2
    port: 53
    timeout: 5
  register: result_testbed
  ignore_errors: true

- name: Set nameserver in resolv.conf to 192.168.178.2
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 192.168.178.2
    backup: yes
  become: true
  when: result_testbed is succeeded and (result_production is failed or result_production is skipped)

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- meta: flush_handlers

- name: Uncomment no-hosts in /etc/dnsmasq.conf
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^#no-hosts'
    line: 'no-hosts'
    
- name: Configure dnsmasq
  blockinfile:
    path: /etc/dnsmasq.conf
    block: |
      server={{ upstream_dns }}#53
      address=/{{ jitsi_fqdn }}/10.0.0.2
      interface=eth0
  notify: Restart dnsmasq