
- name: Enable Jitsi Nginx configuration file
  become: true
  file:
    src: /etc/nginx/sites-available/{{ jitsi_fqdn }}.conf
    dest: /etc/nginx/sites-enabled/{{ jitsi_fqdn }}.conf
    state: link
    
- name: Enable default Nginx configuration file
  become: true
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    
- name: Reload Nginx configuration
  become: true
  systemd:
    name: nginx
    state: reloaded

# Coturn is needed for direct P2P connections between clients. It is used as a STUN/TURN server.
# In a locat network, it is not needed. 
- name: Restart Coturn
  become: true
  systemd:
    name: coturn
    state: stopped
    enabled: no

- name: Enable and start Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Restart Jitsi Meet
  become: true
  service:
    name: jitsi-videobridge2
    state: restarted