- name: Add ip address to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "10.0.0.2 {{ jitsi_fqdn }}"
    state: present
  tags: hosts
- name: Install OpenJDK 8
  apt:
    name: ['openjdk-8-jdk-headless', 'openjdk-8-jre', 'openjdk-8-jre-headless', 'openjdk-8-jdk']
    state: present

- name: Add Debian repositories for Chromium
  copy:
    dest: /etc/apt/sources.list.d/debian.list
    content: |
      deb [arch=arm64] http://ftp.ch.debian.org/debian bullseye main 
      deb [arch=arm64] http://ftp.ch.debian.org/debian bullseye-updates main 

- name: Add Ubuntu keys for Chromium
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 0E98404D386FA1D9
    - 6ED0E7B82643E131
    - 648ACFD622F3D138
    - 605C66F00D6C9793

- name: Configure package priorities for Chromium
  copy:
    dest: /etc/apt/preferences.d/chromium.pref
    content: |
      # Note: 2 blank lines are required between entries
      Package: *
      Pin: release a=eoan
      Pin-Priority: 500

      Package: *
      Pin: origin "deb.debian.org"
      Pin-Priority: 300

      # Pattern includes 'chromium', 'chromium-browser' and similarly
      # named dependencies:
      Package: chromium*
      Pin: origin "deb.debian.org"
      Pin-Priority: 700

- name: Install required packages
  apt:
    name: ['tightvncserver', 'xinit', 'xserver-xorg', 'gnome-tweaks', 'pavucontrol', 'xserver-xorg-legacy', 'ffmpeg', 'curl', 'alsa-utils', 'icewm', 'xdotool', 'xserver-xorg-video-dummy', 'ruby-hocon', 'figlet', 'xdg-utils', 'x11vnc', 'dbus-x11', 'acl', 'xvfb', 'xsel']
    # acl is needed to set proper file permissions and make ansible happy
    # xvfb needed to make x11vnc able to create a virtual display
    state: present

- name: Select OpenJDK 8
  become: true
  command: update-alternatives --config java
  args:
    stdin: '1\n'

- name: Configure X11 to allow any user to start
  lineinfile:
    path: /etc/X11/Xwrapper.config
    regexp: '^allowed_users='
    line: 'allowed_users=anybody'
  tags: x11
    
- name: Ensure X11 xorg.conf.d directory exists
  become: true
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
  tags: x11
- name: Update Xwrapper.config
  become: true
  lineinfile:
    path: /etc/X11/Xwrapper.config
    regexp: "^#?allowed_users="
    line: "allowed_users=anybody"
    state: present
  tags: x11

- name: Prevent screen from going blank
  become: true
  copy:
    dest: /etc/X11/xorg.conf.d/10-monitor.conf
    content: |
      Section "ServerFlags"
          Option "BlankTime" "0"
          Option "StandbyTime" "0"
          Option "SuspendTime" "0"
          Option "OffTime" "0"
      EndSection
    owner: root
    group: root
    mode: '0644'

- name: Install Chromium
  apt:
    name: ['chromium']
    state: present
  notify:
    - Create Chrome policies directory

- name: Create Chrome policies directory
  become: true
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
  notify:
    - Create Chrome policies file

- name: Create Chrome policies file
  become: true
  file:
    path: /etc/opt/chrome/policies/managed/managed_policies.json
    state: touch
  # notify:
  #   - Add Chrome security policy

- name: Add Chrome security policy
  become: true
  lineinfile:
    path: /etc/opt/chrome/policies/managed/managed_policies.json
    line: '{ "CommandLineFlagSecurityWarningsEnabled": false }'

- name: Modify /etc/pulse/default.pa
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-stream-restore$'
    line: 'load-module module-stream-restore restore_device=false'
- name: Create /etc/pulse/default.pa.d/unix_socket.pa for pulseaudio
  become: true
  file:
    path: /etc/pulse/default.pa.d/unix_socket.pa
    state: touch
    owner: root
    group: root
    mode: '0644'
    content: |
      load-module module-native-protocol-unix auth-group=audio socket=/tmp/pulse-socket
- name: Update /etc/pulse/daemon.conf
  blockinfile:
    path: /etc/pulse/daemon.conf
    block: |
      allow-exit = no
      exit-idle-time = -1
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
