---
# tasks file for base_infra
- name: Modify /etc/pulse/default.pa
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-stream-restore$'
    line: 'load-module module-stream-restore restore_device=false'
- name: Create /etc/pulse/default.pa.d/unix_socket.pa for pulseaudio
  become: true
  file:
    path: /etc/pulse/default.pa.d/unix_socket.pa
    state: touch
    owner: root
    group: root
    mode: '0644'
    content: |
      load-module module-native-protocol-unix auth-group=audio socket=/tmp/pulse-socket
- name: Update /etc/pulse/daemon.conf
  blockinfile:
    path: /etc/pulse/daemon.conf
    block: |
      allow-exit = no
      exit-idle-time = -1
    marker: "# {mark} ANSIBLE MANAGED BLOCK"