- name: Check if required variables are defined
  assert:
    that: "{{ item }} is defined"
    fail_msg: "The required variable '{{ item }}' is not defined"
  loop:
    - jitsi_fqdn
    - upstream_dns

- name: Check if required environment variables are defined
  assert:
    that: "lookup('env', item) != ''"
    fail_msg: "The required environment variable '{{ item }}' is not defined"
  loop:
    - WIFI_SECRET