- name: Check if required variables are defined
  assert:
    that: "{{ item }} is defined"
    fail_msg: "The required variable '{{ item }}' is not defined"
  loop:
    - jitsi_fqdn
    - upstream_dns
  tags: quick_build